id: 
name: GitOps.PullRequestIssueManagement
description: GitOps.PullRequestIssueManagement primitive
owner: 
resource: repository
disabled: false
where: 
configuration:
  resourceManagementConfiguration:

    eventResponderTasks:

    - description: Auto-approve/merge automated merge PRs
      triggerOnOwnActions: false
      if:
      - payloadType: Pull_Request
      - isPullRequest
      - isActivitySender:
          user: github-actions[bot]
          issueAuthor: False
      - or:
        - titleContains:
            pattern: "[automated] Merge branch"
            isRegex: False
        - titleContains:
            pattern: "[automated] Update main version"
            isRegex: False
      - isAction:
          action: Opened
      then:
      - approvePullRequest:
          comment: Auto-approve
      - enableAutoMerge:
          mergeMethod: merge

    - description: Auto-approve/merge automated localization PRs
      triggerOnOwnActions: false
      if:
      - payloadType: Pull_Request
      - isPullRequest
      - isActivitySender:
          user: dotnet-bot
          issueAuthor: False
      - titleContains:
          pattern: "Localization result based on"
          isRegex: False
      - isAction:
          action: Opened
      then:
      - approvePullRequest:
          comment: Auto-approve
      - enableAutoMerge:
          mergeMethod: merge

    - description: Add "untriaged" label to issues when opened
      triggerOnOwnActions: false
      if:
      - payloadType: Issues
      - or:
        - isAction:
            action: Opened
      then:
      - addLabel:
          label: untriaged

    - description: Add "OmniSharp" label to issues filed with OmniSharp enabled
      triggerOnOwnActions: false
      if:
      - payloadType: Issues
      - isAction:
          action: Opened
      - bodyContains:
          pattern: "**Using OmniSharp**: true"
          isRegex: False
      then:
      - addLabel:
          label: OmniSharp

onFailure: 
onSuccess: