<Project Sdk="Microsoft.NET.Sdk">
 <ItemGroup>
  <ProjectReference Include="..\lib\lib.csproj" />
  <JsonSchemaSegment Include="schemas\aspire.schema.json"
                     FilePathPattern="appsettings\..*json" />
  <JsonSchemaSegment Include="schemas\yarp.schema.json"
                     FilePathPattern="appsettings\..*json" />
 </ItemGroup>
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>$(LowestSupportedTargetFramework)</TargetFramework>
  </PropertyGroup>

</Project>
