# Merges any changes from release/prerelease to main (e.g. servicing changes)

name: Flow release/prerelease changes to main
on:
  push:
   branches:
     - 'release'
     - 'prerelease'

permissions:
  contents: write
  pull-requests: write

jobs:
  check-script:
    uses: dotnet/arcade/.github/workflows/inter-branch-merge-base.yml@main
    with:
      configuration_file_path: '.config/branch-merge.json'
