name: Update CHANGELOG
on:
  workflow_dispatch:
  schedule:
    # Runs every Tuesday at 9 PM Pacific Time (5 AM UTC Wednesday)
    - cron: '0 5 * * 3'

permissions:
  contents: write
  pull-requests: write

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2
        with:
          fetch-depth: 0
      - name: Install roslyn-tools
        run: dotnet tool install -g Microsoft.RoslynTools --prerelease --source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json
      - name: Install NodeJS
        uses: actions/setup-node@38e0b6e68b4c852a5500a94740f0e535e0d7ba54 # v4
        with:
          node-version: '24.x'
      - name: Install dependencies
        run: npm ci
      - name: Update CHANGELOG
        run: npm run updateChangelog
      - name: Create update PR
        uses: peter-evans/create-pull-request@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update ${{ github.ref_name }} CHANGELOG
          title: '[automated] Update ${{ github.ref_name }} CHANGELOG'
          branch: merge/update-${{ github.ref_name }}-changelog
